export const LABELS = {
  appTitle: 'F1 Dashboard',
  appLogo: '🏎',
  notFoundTitle: '404 — Page Not Found',
  notFoundMessage: 'The page you are looking for does not exist.',
  notFoundBack: 'Back to Home',
  seasonSelector: 'Season',
  seasonSelectorPlaceholder: '2026',
  pageHome: 'Home',
  pageCalendar: 'Calendar',
  pageStandings: 'Standings',
  pageDashboard: 'Dashboard',
  pageRaceResults: 'Race Results',
  pageHomeDescription: 'Season overview — coming soon.',
  pageCalendarDescription: 'Race calendar — coming soon.',
  pageStandingsDescription: 'Driver and constructor standings — coming soon.',
  pageDashboardDescription: 'Charts and summary — coming soon.',
  pageRaceResultsMeta: 'Season {season}, Round {round}',
  raceHeaderTitle: 'Round {round} — {raceName} {season}',
  backToCalendar: 'Back to Calendar',
  noResults: 'No results available for this race.',
  invalidRaceParams: 'Invalid race URL.',
  loading: 'Loading...',
  error: 'Something went wrong. Please try again.',
  noRaces: 'No races found for this season.',
  retry: 'Retry',
  calendarEmpty: 'No races scheduled.',
  standingsTabDrivers: 'Drivers',
  standingsTabConstructors: 'Constructors',
  noStandings: 'No standings available for this season.',
  homeSeasonOverview: '{season} Season Overview',
  nextRaceTitle: 'Next Race',
  latestResultsTitle: 'Latest Results',
  latestResultsHeader: 'Round {round} — {raceName}',
  noUpcomingRace: 'No upcoming races this season.',
  noCompletedRace: 'No completed races yet.',
  noLatestResults: 'Results not available.',
  viewCalendar: 'View Calendar',
  viewFullResults: 'View Full Results',
  quickLinksTitle: 'Quick Links',
  quickLinkCalendarDescription: 'All races',
  quickLinkStandingsDescription: 'Driver & constructor points',
  quickLinkDashboardDescription: 'Charts & summary',
  countdownFormat: '{days} days, {hours} hours, {minutes} min',
  countdownSoon: 'Starting soon',
  countdownPast: 'Race started',
  dashboardSeasonSummary: '{season} Season Summary',
  summaryDriverLeader: 'Driver Leader',
  summaryConstructorLeader: 'Constructor Leader',
  summaryNextRace: 'Next Race',
  summaryLastRaceWinner: 'Last Race Winner',
  summaryDriverMeta: '{points} pts · {constructor}',
  summaryConstructorMeta: '{points} pts · {wins} wins',
  summaryNextRaceRound: 'Round {round} — {raceName}',
  summaryLastRaceMeta: 'Round {round} — {raceName}',
  noDriverLeader: 'No driver standings available.',
  noConstructorLeader: 'No constructor standings available.',
  noNextRace: 'No upcoming races.',
  noLastRaceWinner: 'No race results yet.',
  chartDriverPointsTitle: 'Driver Points — Top 10',
  chartConstructorPointsTitle: 'Constructor Points — Top 10',
  chartAxisPoints: 'Points',
  chartNoData: 'No chart data available.',
} as const
