export const LABELS = {
  appTitle: 'F1 Dashboard',
  appLogo: '🏎',
  notFoundTitle: '404 — Page Not Found',
  notFoundMessage: 'The page you are looking for does not exist.',
  notFoundBack: 'Back to Home',
  seasonSelector: 'Season',
  seasonSelectorPlaceholder: '2026',
  pageHome: 'Home',
  pageCalendar: 'Calendar',
  pageStandings: 'Standings',
  pageDashboard: 'Dashboard',
  pageRaceResults: 'Race Results',
  pageHomeDescription: 'Season overview — coming soon.',
  pageCalendarDescription: 'Race calendar — coming soon.',
  pageStandingsDescription: 'Driver and constructor standings — coming soon.',
  pageDashboardDescription: 'Charts and summary — coming soon.',
  pageRaceResultsMeta: 'Season {season}, Round {round}',
  loading: 'Loading...',
  error: 'Something went wrong. Please try again.',
  noRaces: 'No races found for this season.',
  retry: 'Retry',
  calendarEmpty: 'No races scheduled.',
} as const
